# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import communication_with_worker_pb2 as communication__with__worker__pb2


class WorkerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ActiveHeartbeat = channel.unary_unary(
                '/WorkerService/ActiveHeartbeat',
                request_serializer=communication__with__worker__pb2.IdleHeartbeatRequest.SerializeToString,
                response_deserializer=communication__with__worker__pb2.IdleHeartbeatResponse.FromString,
                )
        self.DatasetTransfer = channel.unary_unary(
                '/WorkerService/DatasetTransfer',
                request_serializer=communication__with__worker__pb2.DatasetRequest.SerializeToString,
                response_deserializer=communication__with__worker__pb2.DatasetResponse.FromString,
                )


class WorkerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ActiveHeartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DatasetTransfer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ActiveHeartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.ActiveHeartbeat,
                    request_deserializer=communication__with__worker__pb2.IdleHeartbeatRequest.FromString,
                    response_serializer=communication__with__worker__pb2.IdleHeartbeatResponse.SerializeToString,
            ),
            'DatasetTransfer': grpc.unary_unary_rpc_method_handler(
                    servicer.DatasetTransfer,
                    request_deserializer=communication__with__worker__pb2.DatasetRequest.FromString,
                    response_serializer=communication__with__worker__pb2.DatasetResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'WorkerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class WorkerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ActiveHeartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/WorkerService/ActiveHeartbeat',
            communication__with__worker__pb2.IdleHeartbeatRequest.SerializeToString,
            communication__with__worker__pb2.IdleHeartbeatResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DatasetTransfer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/WorkerService/DatasetTransfer',
            communication__with__worker__pb2.DatasetRequest.SerializeToString,
            communication__with__worker__pb2.DatasetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
