# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import communication_with_bootstrap_pb2 as communication__with__bootstrap__pb2

GRPC_GENERATED_VERSION = '1.64.0'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in communication_with_bootstrap_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class BootstrapServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.JoinNetwork = channel.unary_unary(
                '/BootstrapService/JoinNetwork',
                request_serializer=communication__with__bootstrap__pb2.JoinRequest.SerializeToString,
                response_deserializer=communication__with__bootstrap__pb2.JoinResponse.FromString,
                _registered_method=True)
        self.ActiveHeartbeat = channel.unary_unary(
                '/BootstrapService/ActiveHeartbeat',
                request_serializer=communication__with__bootstrap__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=communication__with__bootstrap__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.GetIdleWorkers = channel.unary_unary(
                '/BootstrapService/GetIdleWorkers',
                request_serializer=communication__with__bootstrap__pb2.Empty.SerializeToString,
                response_deserializer=communication__with__bootstrap__pb2.IdleWorkersResponse.FromString,
                _registered_method=True)
        self.UpdateIdleWorker = channel.unary_unary(
                '/BootstrapService/UpdateIdleWorker',
                request_serializer=communication__with__bootstrap__pb2.UpdateIdleRequest.SerializeToString,
                response_deserializer=communication__with__bootstrap__pb2.Empty.FromString,
                _registered_method=True)
        self.UpdateNotIdleWorker = channel.unary_unary(
                '/BootstrapService/UpdateNotIdleWorker',
                request_serializer=communication__with__bootstrap__pb2.UpdateIdleRequest.SerializeToString,
                response_deserializer=communication__with__bootstrap__pb2.Empty.FromString,
                _registered_method=True)
        self.UpdateStorage = channel.unary_unary(
                '/BootstrapService/UpdateStorage',
                request_serializer=communication__with__bootstrap__pb2.UpdateStorageRequest.SerializeToString,
                response_deserializer=communication__with__bootstrap__pb2.UpdateStorageResponse.FromString,
                _registered_method=True)
        self.GetStorage = channel.unary_unary(
                '/BootstrapService/GetStorage',
                request_serializer=communication__with__bootstrap__pb2.GetStorageRequest.SerializeToString,
                response_deserializer=communication__with__bootstrap__pb2.GetStorageResponse.FromString,
                _registered_method=True)


class BootstrapServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def JoinNetwork(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ActiveHeartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetIdleWorkers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateIdleWorker(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateNotIdleWorker(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateStorage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStorage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BootstrapServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'JoinNetwork': grpc.unary_unary_rpc_method_handler(
                    servicer.JoinNetwork,
                    request_deserializer=communication__with__bootstrap__pb2.JoinRequest.FromString,
                    response_serializer=communication__with__bootstrap__pb2.JoinResponse.SerializeToString,
            ),
            'ActiveHeartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.ActiveHeartbeat,
                    request_deserializer=communication__with__bootstrap__pb2.HeartbeatRequest.FromString,
                    response_serializer=communication__with__bootstrap__pb2.HeartbeatResponse.SerializeToString,
            ),
            'GetIdleWorkers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIdleWorkers,
                    request_deserializer=communication__with__bootstrap__pb2.Empty.FromString,
                    response_serializer=communication__with__bootstrap__pb2.IdleWorkersResponse.SerializeToString,
            ),
            'UpdateIdleWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateIdleWorker,
                    request_deserializer=communication__with__bootstrap__pb2.UpdateIdleRequest.FromString,
                    response_serializer=communication__with__bootstrap__pb2.Empty.SerializeToString,
            ),
            'UpdateNotIdleWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateNotIdleWorker,
                    request_deserializer=communication__with__bootstrap__pb2.UpdateIdleRequest.FromString,
                    response_serializer=communication__with__bootstrap__pb2.Empty.SerializeToString,
            ),
            'UpdateStorage': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateStorage,
                    request_deserializer=communication__with__bootstrap__pb2.UpdateStorageRequest.FromString,
                    response_serializer=communication__with__bootstrap__pb2.UpdateStorageResponse.SerializeToString,
            ),
            'GetStorage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStorage,
                    request_deserializer=communication__with__bootstrap__pb2.GetStorageRequest.FromString,
                    response_serializer=communication__with__bootstrap__pb2.GetStorageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'BootstrapService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('BootstrapService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BootstrapService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def JoinNetwork(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/BootstrapService/JoinNetwork',
            communication__with__bootstrap__pb2.JoinRequest.SerializeToString,
            communication__with__bootstrap__pb2.JoinResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ActiveHeartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/BootstrapService/ActiveHeartbeat',
            communication__with__bootstrap__pb2.HeartbeatRequest.SerializeToString,
            communication__with__bootstrap__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetIdleWorkers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/BootstrapService/GetIdleWorkers',
            communication__with__bootstrap__pb2.Empty.SerializeToString,
            communication__with__bootstrap__pb2.IdleWorkersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateIdleWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/BootstrapService/UpdateIdleWorker',
            communication__with__bootstrap__pb2.UpdateIdleRequest.SerializeToString,
            communication__with__bootstrap__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateNotIdleWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/BootstrapService/UpdateNotIdleWorker',
            communication__with__bootstrap__pb2.UpdateIdleRequest.SerializeToString,
            communication__with__bootstrap__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateStorage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/BootstrapService/UpdateStorage',
            communication__with__bootstrap__pb2.UpdateStorageRequest.SerializeToString,
            communication__with__bootstrap__pb2.UpdateStorageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStorage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/BootstrapService/GetStorage',
            communication__with__bootstrap__pb2.GetStorageRequest.SerializeToString,
            communication__with__bootstrap__pb2.GetStorageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
