# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: communication_with_bootstrap.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"communication_with_bootstrap.proto\"#\n\x07\x41\x64\x64ress\x12\n\n\x02IP\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\t\"2\n\x05Specs\x12\x0b\n\x03\x43PU\x18\x01 \x01(\t\x12\x0b\n\x03RAM\x18\x02 \x01(\t\x12\x0f\n\x07storage\x18\x03 \x01(\t\"?\n\x0bJoinRequest\x12\x19\n\x07\x61\x64\x64ress\x18\x01 \x01(\x0b\x32\x08.Address\x12\x15\n\x05specs\x18\x02 \x01(\x0b\x32\x06.Specs\">\n\x0cJoinResponse\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12 \n\x0e\x65xisting_peers\x18\x02 \x03(\x0b\x32\x08.Address\" \n\x10HeartbeatRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t\"#\n\x11HeartbeatResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"\x07\n\x05\x45mpty\"5\n\x13IdleWorkersResponse\x12\x1e\n\x0cidle_workers\x18\x01 \x03(\x0b\x32\x08.Address2\xa8\x01\n\x10\x42ootstrapService\x12*\n\x0bJoinNetwork\x12\x0c.JoinRequest\x1a\r.JoinResponse\x12\x38\n\x0f\x41\x63tiveHeartbeat\x12\x11.HeartbeatRequest\x1a\x12.HeartbeatResponse\x12.\n\x0eGetIdleWorkers\x12\x06.Empty\x1a\x14.IdleWorkersResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'communication_with_bootstrap_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ADDRESS']._serialized_start=38
  _globals['_ADDRESS']._serialized_end=73
  _globals['_SPECS']._serialized_start=75
  _globals['_SPECS']._serialized_end=125
  _globals['_JOINREQUEST']._serialized_start=127
  _globals['_JOINREQUEST']._serialized_end=190
  _globals['_JOINRESPONSE']._serialized_start=192
  _globals['_JOINRESPONSE']._serialized_end=254
  _globals['_HEARTBEATREQUEST']._serialized_start=256
  _globals['_HEARTBEATREQUEST']._serialized_end=288
  _globals['_HEARTBEATRESPONSE']._serialized_start=290
  _globals['_HEARTBEATRESPONSE']._serialized_end=325
  _globals['_EMPTY']._serialized_start=327
  _globals['_EMPTY']._serialized_end=334
  _globals['_IDLEWORKERSRESPONSE']._serialized_start=336
  _globals['_IDLEWORKERSRESPONSE']._serialized_end=389
  _globals['_BOOTSTRAPSERVICE']._serialized_start=392
  _globals['_BOOTSTRAPSERVICE']._serialized_end=560
# @@protoc_insertion_point(module_scope)
