# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import communication_with_bootstrap_pb2 as communication__with__bootstrap__pb2


class BootstrapServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.JoinNetwork = channel.unary_unary(
                '/BootstrapService/JoinNetwork',
                request_serializer=communication__with__bootstrap__pb2.JoinRequest.SerializeToString,
                response_deserializer=communication__with__bootstrap__pb2.JoinResponse.FromString,
                )
        self.ActiveHeartbeat = channel.unary_unary(
                '/BootstrapService/ActiveHeartbeat',
                request_serializer=communication__with__bootstrap__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=communication__with__bootstrap__pb2.HeartbeatResponse.FromString,
                )


class BootstrapServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def JoinNetwork(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ActiveHeartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BootstrapServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'JoinNetwork': grpc.unary_unary_rpc_method_handler(
                    servicer.JoinNetwork,
                    request_deserializer=communication__with__bootstrap__pb2.JoinRequest.FromString,
                    response_serializer=communication__with__bootstrap__pb2.JoinResponse.SerializeToString,
            ),
            'ActiveHeartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.ActiveHeartbeat,
                    request_deserializer=communication__with__bootstrap__pb2.HeartbeatRequest.FromString,
                    response_serializer=communication__with__bootstrap__pb2.HeartbeatResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'BootstrapService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BootstrapService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def JoinNetwork(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BootstrapService/JoinNetwork',
            communication__with__bootstrap__pb2.JoinRequest.SerializeToString,
            communication__with__bootstrap__pb2.JoinResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ActiveHeartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BootstrapService/ActiveHeartbeat',
            communication__with__bootstrap__pb2.HeartbeatRequest.SerializeToString,
            communication__with__bootstrap__pb2.HeartbeatResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
